TypeError: Member length is read-only and cannot be used to resize arrays.USED PUSH / POP INSTEAD OF TRYING TO ALTER ARRAY WITH LENGTH ATTRIBUTE. TypeError: sha3 has been deprecated in favour of keccak256. CHANGED SHA3 TO KECCAK256 AND ADDED COMMAND ABI.ENCODEPACKED TO CONCATENATE ARGUMENTS. TypeError: Return arguments required. EITHER REMOVED RETURN STATEMENT OR CHANGED TO RETURN TRUE. TypeError: send and transfer are only available for objects of type address payable, not address. TYPECASTED P.CREATOR TO PAYABLE. ALSO IN LAST COMMIT KEYWORDS MEMORY AND STORAGE WERE ADDED TO VARIABLE DECLARATIONS TO MANAGE DATA LOCATIONS.